### ISSUE TITLE
FreeCAD 27936 Path workbench : Ramp Entry Dressup fails

### ISSUE THREAD

**Issue by suromark** [FreeCAD/FreeCAD-Bundle#96]
Since updating from 26479 to 27809 / 27936 (running on Mac OS X), the Ramp Entry dressup in the path workbench fails with this error message in the console:

> Running the Python command 'Path_DressupRampEntry' failed:
> Traceback (most recent call last):
>   File "/Applications/FreeCAD-27936.app/Contents/Resources/Mod/Path/PathScripts/PathDressupRampEntry.py", line 945, in Activated
>     FreeCADGui.doCommand(
>   File "<string>", line 1, in <module>
>   File "/Applications/FreeCAD-27936.app/Contents/Resources/Mod/Path/PathScripts/PathDressupRampEntry.py", line 106, in __init__
>     setattr(obj, n[0], n[1])
> 
> 'FeaturePython' object has no attribute 'Object'

Executing the operation on the same document file in 26479 makes the feature work again.

**Comment by luzpaz** [comment]
Not the place for ticket. Please first post to the Path forum
